import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header/Header";

export const metadata: Metadata = {
  title: "Silicon backoffice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://kit.fontawesome.com/81af572429.css"
          crossOrigin="anonymous"
        />
      </head>
      <body>
        
        <div className="wrapper">
          <Header />
          {children}
          </div>
      </body>
    </html>
  );
}
